---
title: "CodeBook"
author: "SEH"
date: "9/13/2020"
output: html_document
---
This is the codebook for the Getting and Cleaning data project.

Human Activity Recognition Using Smartphones Dataset
========================================================
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones


Here are the data for the project:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip


Variables and data transformation
==================================
1. Assign each data to variables
 - features <- features.txt : 561 rows, 2 columns
   (The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ.)
 - activities <- activity_labels.txt : 6 rows, 2 columns
   (List of 6 activities performed when the corresponding measurements were taken and its labels
 - subject_test <- subject_test.txt : 2947 rows, 1 column
   (30% :  9/30 subjects' data observed used for test) 
 - subject_train <- subject_train.txt : 7352 rows, 1 column
   (70% :  21/30 subjects' data observed used for train) 
 - x_test <- X_test.txt : 2947 rows, 561 columns
   (features test data)
 - y_test <- y_test.txt : 2947 rows, 1 columns
   (test data of activities’ labels)
 - x_train <- X_train.txt : 7352 rows, 561 columns
   (features train data)
 - y_train <- y_train.txt : 7352 rows, 1 columns
   (train data of activities’labels)

2. Merged data 
 - x (10299 rows, 561 columns) ; created by merging x_train and x_test using rbind() function
 - y (10299 rows, 1 column) ; created by merging y_train and y_test using rbind() function
 - subject (10299 rows, 1 column) ; created by merging subject_train and subject_test using rbind() function
 - merged_data (10299 rows, 563 column); created by merging Subject, Y and X using cbind() function

